### ISSUE TITLE
VoxelSpace.html

### ISSUE THREAD

**Issue by JohnLetey** [s-macke/VoxelSpace#10]
When I cloned your repo and opened `VoxelSpace.html`, for some reason I get this:

<img width="1272" alt="screen shot 2017-12-03 at 12 29 53 pm" src="https://user-images.githubusercontent.com/30328854/33528880-b537e21c-d825-11e7-8350-2b0d281c3b93.png">

Do you know why I'm getting this? Please note that I'm on a MacBook (just that) using High Sierra

**Comment by s-macke** [comment]
I patched the file to fix two problems. Can you try it again please.

**Comment by JohnLetey** [comment]
Sure thing! Trying it now

**Comment by JohnLetey** [comment]
Nope. Unfortunately, I get the same image. Do I not have some dependencies?

**Comment by s-macke** [comment]
Can you open your Javascript console (probably key F12 in your browser) and then refresh the page (key F5). There might be some error messages written by the browser.

**Comment by JohnLetey** [comment]
I'll try that

**Comment by JohnLetey** [comment]
Here are the errors I get:

<img width="1277" alt="screen shot 2017-12-03 at 3 10 16 pm" src="https://user-images.githubusercontent.com/30328854/33530397-2282a04e-d83c-11e7-9c9c-c9ca5a7b35d7.png">

**Comment by s-macke** [comment]
Ok, the problem is, that you are try to open the web page locally. This works in some browsers, but not in all of them. Some prevent specific features when run local webpages. Please take a look at the following link and follow their suggestions.

https://stackoverflow.com/questions/4556429/disabling-same-origin-policy-in-safari

**Comment by JohnLetey** [comment]
Thanks! That worked!
